accounts/urls.py
from django.urls import path
from .views import LoginPage, SignUpView

urlpatterns = [
    path("login/", LoginPage.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("post.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("post.urls")),
]

post/urls.py
from django.urls import path
from .views import HomePage, AddPost, PostDetailView, PostDeleteView, PostEditView

urlpatterns = [
    path("", HomePage.as_view(), name="home"),
    path("add_post/", AddPost.as_view(), name="add_post"),
    path("<int:pk>/delete_post/", PostDeleteView.as_view(), name="delete_post"),
    path("<int:pk>/edit/", PostEditView.as_view(), name="edit_post"),
    path("<int:pk>/detail/", PostDetailView.as_view(), name="detail_post"),
]

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey("auth.user", on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title.title()

    def get_absolute_url(self):
        return reverse("detail_post", kwargs={"pk": self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    author = models.ForeignKey("auth.user", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.body[:10]

accounts/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
    AuthenticationForm,
    UsernameField,
    UserCreationForm,
)
from django.utils.translation import gettext_lazy as _
from django import forms


class CustomUserLoginForm(AuthenticationForm):

    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "placeholder": "Username",
                "class": "form-control fields",
            }
        )
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "placeholder": "Password",
                "class": "form-control fields",
            }
        ),
    )


class CustomSignUpForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "placeholder": "Username",
                "class": "form-control fields",
            }
        )
    )
    email = forms.EmailField(
        label=_("Email"),
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control fields",
            }
        ),
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control fields",
                "placeholder": "password",
            }
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control fields",
                "placeholder": "password",
            }
        ),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserLoginForm, CustomSignUpForm


class LoginPage(LoginView):
    authentication_form = CustomUserLoginForm


class SignUpView(CreateView):
    form_class = CustomSignUpForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

post/views.py
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
    FormView,
)
from django.views import View
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from .form import CustomAddPostForm, CommentForm
from .models import Post


class HomePage(ListView):
    model = Post
    template_name = "home.html"


class AddPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "edit_add_post.html"
    form_class = CustomAddPostForm

    def form_valid(self, form):
        form.instance.title = form.instance.title.title()
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDetailView(LoginRequiredMixin, View):
    model = Post
    template_name = "detail_post.html"

    def post(self, request, *args: str, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)

    def get(self, request, *args: str, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)


class CommentGet(DetailView):
    model = Post
    template_name = "detail_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Post
    form_class = CommentForm
    template_name = "detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        post = self.get_object()
        return reverse_lazy("detail_post", kwargs={"pk": post.pk})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "delete_post.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        object = self.get_object()
        return object.author == self.request.user


class PostEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "edit_add_post.html"
    form_class = CustomAddPostForm

    def test_func(self):
        object = self.get_object()
        return object.author == self.request.user

    def form_valid(self, form):
        form.instance.title = form.instance.title.title()
        return super().form_valid(form)

templates/base.html
<html>

<head>
    <title>{% block title %} {% endblock title%}</title>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}
    {% endblock head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>
        document.addEventListener('click', function (event) {

            if (!event.target.closest('#menu')) {
                closeSidebar();
                console.log("h");
            }
            else {
                console.log("he");
                expand();
            }

        });

        function closeSidebar() {
            const menu = document.getElementById("menu");
            menu.className = "side-bar";
        }

        function expand() {

            const menu = document.getElementById("menu")
            console.log(menu.className);
            if (menu.className == "side-bar-expand") {
                console.log("sup")
                menu.className = "side-bar"
            }
            else {
                menu.className = "side-bar-expand";
                console.log("heh")
            }
        }



    </script>

</head>
{% block header %}
<header>

</header>
{% endblock header %}

<body>
    <!-- <header> -->
    <div id="menu" class="side-bar">
        <ul>
            <li data-image="menu">Menu</li>
            <a href="{% url 'home' %}">
                <li data-image="home">Home</li>
            </a>
            {% if user.is_authenticated %}
            <a href="{% url 'add_post' %}">
                <li data-image="add">Add</li>
            </a>
            <a href="{% url 'logout' %}">
                <li data-image="logout">logout</li>
            </a>
            {% else %}
            <a href="{% url 'login' %}">
                <li data-image="login">login</li>
            </a>

            <a href="{% url 'signup' %}">

                <li data-image="signup">signup
                </li>
            </a>
            {% endif %}
        </ul>
    </div>
    <!-- </header> -->
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/delete_post.html
{% extends 'base.html' %}
{% block content %}
<div id="add-form" class="container">
    <h3>Are you sure you want to delete this post?</h3>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="confirm" class="btn btn-danger">
    </form>
</div>
{% endblock content %}

templates/detail_post.html
{% extends 'base.html' %}


{% block content %}
<div class="article">
    <h1>{{post.title}}</h1>
    <p> {{ post.body }} </p>
    <span class="article-author align-right">
        <p>-{{ post.author }}</p>
    </span>
    <div class="nav-detail">
        {% if post.author == user %}
        <a class="nav-left btn  btn-primary article-author" href="{% url 'edit_post' post.pk%}">edit</a>
        <a class="nav-right btn btn-danger article-author" href="{% url 'delete_post' post.pk %}">delete</a>
        {% endif %}
    </div>
    <hr>
    <div>
        <h2>Comments {{ post.comment_set.all| length }}</h2>

        {% for comment in post.comment_set.all %}
        <div class="comment">
            <p><b>{{ comment.author }}</b> <br> {{ comment.body }}</p>
        </div>
        {% endfor %}
    </div>
    <hr>


    <div class="form-container">
        <form action="" method="post">
            {%for field in form%}
            {% csrf_token %}
            {{field}}
            {% endfor%}
            <button type="submit" class="btn btn-primary col-sm-3">Post</button>
        </form>
    </div>

</div>
{% endblock content %}

templates/edit_add_post.html
{% extends 'base.html'%}


{% block content %}
<div id="add-form" class="container">
    <form action="" method="post">
        {%for field in form%}
        {% csrf_token %}
        <span style="color: aliceblue;">{{field.label}}:</span>
        {{field}}
        {% endfor%}
        <button type="submit" class="btn btn-primary col-sm-3">Save</button>
    </form>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block title %} home {% endblock title%}

{% block content %}
{% if post_list %}
{%for post in post_list%}
<div class="post-block">
    <h2>{{ post.title }} | <span class="text-muted"> By:{{post.author}} </span></h2>
    <blockquote>{{post.date}}</blockquote>
    <p>{{ post.body|slice:":100" }}...</p>
    <div class="row">
        <a href="{% url 'detail_post' post.pk %}">
            <button class="col-sm-3 btn btn-primary">Read More</button>
        </a>
    </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}